# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$character"""
right_format = """$all"""
add_newline = true
command_timeout = 1000

[package]
disabled = true

[os]
disabled = false

[character]
success_symbol = "[󱞩](bold blue)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[󱞥](bold blue)"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "

[git_status]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"
version_format = "v${major}.${minor}"
style = "blue"
symbol = " "

[bun]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
version_format = "v${major}.${minor}"
style = "blue"
symbol = " "

[aws]
disabled = true
